[package]
name = "quicksilver-roguelike"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
edition = "2018"

[dependencies]
quicksilver = { version = "0.3.6", default-features = false, features = ["collisions", "complex_shapes", "immi_ui", "fonts", "saving", "rodio"]}
